FROM node:16.17.0-alpine AS builder
USER node
WORKDIR /app

COPY package.json .
RUN yarn install --production

COPY . /app
RUN yarn build


FROM busybox:1.35
RUN adduser -D www
USER www

WORKDIR /app
COPY --from=builder --chown=node:node /app/dist .

EXPOSE 4370
CMD ["busybox", "httpd", "-f", "-v", "-p", "4370"]
