FROM node:20.11.1-alpine AS builder
USER root
WORKDIR /app
RUN yarn add typescript vite

COPY package.json .
COPY yarn.lock .
RUN yarn install

COPY . /app

RUN NODE_OPTIONS=--max_old_space_size=4096 yarn build

FROM busybox:1.35
RUN adduser -D www
USER www
WORKDIR /app
LABEL org.opencontainers.image.description moneeey-frontend
LABEL org.opencontainers.image.title moneeey-frontend

COPY --from=builder --chown=www:www /app/dist .

EXPOSE 4370
CMD ["busybox", "httpd", "-f", "-v", "-p", "4370"]
