version: "3.3"

services:
  frontend:
    build: ./docker
    restart: unless-stopped
    networks:
      - moneeey-network
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/frontend:/app:z

  backend:
    build: ./docker
    restart: unless-stopped
    networks:
      - moneeey-network
    depends_on:
      - couchdb
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/sample.env:/run/secret/dev.env:z
      - ${LOCAL_WORKSPACE_FOLDER:-.}/backend:/app:z

  couchdb:
    image: couchdb:3.2
    restart: unless-stopped
    networks:
      - moneeey-network
    environment:
      - COUCHDB_USER=dev
      - COUCHDB_PASSWORD=dev
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/docker/couchdb_data:/opt/couchdb/data:z
      - ${LOCAL_WORKSPACE_FOLDER:-.}/docker/couchdb.dev.ini:/opt/couchdb/etc/local.d/local.ini:z

  devmail:
    image: maildev/maildev:2.0.5
    restart: unless-stopped
    networks:
      - moneeey-network

  caddy:
    image: caddy:2.6.4-alpine
    restart: unless-stopped
    networks:
      - moneeey-network
    ports:
      - 4280:4280
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/docker/Caddyfile:/etc/caddy/Caddyfile:z
      - ${LOCAL_WORKSPACE_FOLDER:-.}/docker/caddy_data:/data:z
      - ${LOCAL_WORKSPACE_FOLDER:-.}/docker/caddy_config:/config:z

networks:
  moneeey-network:
