version: "3.3"

services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    networks:
      - moneeey-network
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/frontend:/app:z
      - ${LOCAL_WORKSPACE_FOLDER:-.}/docker/volume/frontend_node_modules:/app/node_modules:z

  backend:
    build: ./backend
    restart: unless-stopped
    networks:
      - moneeey-network
    depends_on:
      - couchdb
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/backend/env.example:/run/secret/dev.env:z,ro
      - ${LOCAL_WORKSPACE_FOLDER:-.}/backend:/app:z

  couchdb:
    image: couchdb:3.2
    restart: unless-stopped
    networks:
      - moneeey-network
    environment:
      - COUCHDB_USER=dev
      - COUCHDB_PASSWORD=dev
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/docker/volume/couchdb_data:/opt/couchdb/data:z
      - ${LOCAL_WORKSPACE_FOLDER:-.}/docker/couchdb.dev.ini:/opt/couchdb/etc/local.d/local.ini:z

  caddy:
    image: caddy:2.6.4-alpine
    restart: unless-stopped
    networks:
      - moneeey-network
    ports:
      - 4280:4280
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/docker/Caddyfile:/etc/caddy/Caddyfile:z,ro
      - ${LOCAL_WORKSPACE_FOLDER:-.}/docker/volume/caddy_data:/data:z
      - ${LOCAL_WORKSPACE_FOLDER:-.}/docker/volume/caddy_config:/config:z

networks:
  moneeey-network:
