version: '3'

services:
  frontend:
    build: ./docker
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    ports:
      - '4270:4270'

  backend:
    build: ./docker
    restart: unless-stopped
    depends_on:
      - couchdb
    volumes:
      - ./sample.env:/run/secret/prod.env:ro
      - ./backend:/app
    ports:
      - '4269:4269'

  couchdb:
    image: couchdb:3.2
    restart: unless-stopped
    environment:
      - COUCHDB_USER=dev
      - COUCHDB_PASSWORD=dev
    ports:
      - '5984:5984'
      - '4369:4369'
      - '9100:9100'
    volumes:
      - ./docker/couchdb_data:/opt/couchdb/data
      - ./docker/couchdb.dev.ini:/opt/couchdb/etc/local.d/local.ini

  devmail:
    image: maildev/maildev:2.0.5
    restart: unless-stopped
    ports:
      - '1080:1080'
      - '1025:1025'

volumes:
  couchdb_data:
    driver: local
