FROM node:16.17.0-alpine AS builder
USER node
WORKDIR /app

COPY package.json .
RUN yarn install --production

COPY . /app
RUN yarn build


FROM node:16.17.0-alpine
USER node
WORKDIR /app

COPY --from=builder --chown=node:node /app/node_modules ./node_modules
COPY --from=builder --chown=node:node /app/dist .

EXPOSE 4369
ENV PORT 4369
CMD ["node", "server.js"]
