version: '3.3'

networks:
  web:
    external: true

services:
  frontend:
    image: FRONTEND_IMAGE
    restart: unless-stopped

  backend:
    image: BACKEND_IMAGE
    restart: unless-stopped
    volumes:
      - /home/ubuntu/moneeey/env:/run/secret/prod.env:ro

  couchdb:
    image: couchdb:3.2
    restart: unless-stopped
    env_file:
      - /home/ubuntu/moneeey/env
    volumes:
      - /home/ubuntu/moneeey/couchdb_data:/opt/couchdb/data
      - /home/ubuntu/moneeey/couchdb.prod.ini:/opt/couchdb/etc/local.d/local.ini

  caddy:
    image: caddy:2.6.4-alpine
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.moneeey.rule=Host(`moneeey.io`)"
      - "traefik.http.routers.moneeey.tls.certresolver=le"
    networks:
      - web
    volumes:
      - /home/ubuntu/moneeey/Caddyfile.prod:/etc/caddy/Caddyfile:z,ro
      - /home/ubuntu/moneeey/caddy_data:/data:z
      - /home/ubuntu/moneeey/caddy_config:/config:z

