version: '3.3'

networks:
  web:
    external: true

services:
  frontend:
    image: FRONTEND_IMAGE
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.moneeey-frontend.rule=Host(`moneeey.io`) && !PathPrefix(`/api`)"
      - "traefik.http.routers.moneeey-frontend.tls.certresolver=le"

  backend:
    image: BACKEND_IMAGE
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.moneeey-backend.rule=Host(`moneeey.io`) && PathPrefix(`/api`)"
      - "traefik.http.routers.moneeey-backend.tls.certresolver=le"
    depends_on:
      - couchdb
    volumes:
      - /root/bt3/moneeey/env:/run/secret/prod.env:ro

  couchdb:
    image: couchdb:3.2
    restart: unless-stopped
    environment:
      - COUCHDB_USER=prod
      - COUCHDB_PASSWORD=prod
    volumes:
      - /root/bt3/moneeey/couchdb_data:/opt/couchdb/data
      - /root/bt3/moneeey/couchdb.prod.ini:/opt/couchdb/etc/local.d/local.ini
