export default {
	menu: {
		title: { en: "Moneeey", pt: "Moneeey", es: "Moneeey", hi: "मनी", cn: "钱" },
		search: {
			en: "Search",
			pt: "Pesquisar",
			es: "Buscar",
			hi: "खोजें",
			cn: "搜索",
		},
		dashboard: {
			en: "Dashboard",
			pt: "Sumário",
			es: "Panel de control",
			hi: "डैशबोर्ड",
			cn: "仪表盘",
		},
		transactions: {
			en: "Transactions",
			pt: "Transações",
			es: "Transacciones",
			hi: "लेन-देन",
			cn: "交易",
		},
		unassigned: {
			en: (amount: number) => `Unassigned (${amount})`,
			pt: (amount: number) => `Não atribuído (${amount})`,
			es: (amount: number) => `Sin asignar (${amount})`,
			hi: (amount: number) => `असाइन नहीं किया गया (${amount})`,
			cn: (amount: number) => `未分配 (${amount})`,
		},
		balance: {
			en: (amount: string) => `Balance: ${amount}`,
			pt: (amount: string) => `Saldo: ${amount}`,
			es: (amount: string) => `Saldo: ${amount}`,
			hi: (amount: string) => `शेष राशि: ${amount}`,
			cn: (amount: string) => `余额: ${amount}`,
		},
		all_transactions: {
			en: "All transactions",
			pt: "Todas as transações",
			es: "Todas las transacciones",
			hi: "सभी लेन-देन",
			cn: "所有交易",
		},
		import: {
			en: "Import",
			pt: "Importar",
			es: "Importar",
			hi: "आयात करें",
			cn: "导入",
		},
		budget: {
			en: "Budget",
			pt: "Orçamento",
			es: "Presupuesto",
			hi: "बजट",
			cn: "预算",
		},
		reports: {
			en: "Reports",
			pt: "Relatórios",
			es: "Informes",
			hi: "रिपोर्ट",
			cn: "报告",
		},
		settings: {
			en: "Settings",
			pt: "Configurações",
			es: "Configuración",
			hi: "सेटिंग्स",
			cn: "设置",
		},
		currencies: {
			en: "Currencies",
			pt: "Moedas",
			es: "Monedas",
			hi: "मुद्राएँ",
			cn: "货币",
		},
		payees: {
			en: "Payees",
			pt: "Beneficiários",
			es: "Beneficiarios",
			hi: "भुगतानकर्ता",
			cn: "收款人",
		},
		accounts: {
			en: "Accounts",
			pt: "Contas",
			es: "Cuentas",
			hi: "खाते",
			cn: "账户",
		},
		preferences: {
			en: "Preferences",
			pt: "Preferências",
			es: "Preferencias",
			hi: "प्राथमिकताएँ",
			cn: "偏好设置",
		},
		start_tour: {
			en: "Start tour",
			pt: "Iniciar tour",
			es: "Comenzar tour",
			hi: "यात्रा शुरू करें",
			cn: "开始游览",
		},
		sync_ONLINE: {
			en: "Online",
			pt: "Online",
			es: "En línea",
			hi: "ऑनलाइन",
			cn: "在线",
		},
		sync_OFFLINE: {
			en: "Offline",
			pt: "Offline",
			es: "Fuera de línea",
			hi: "ऑफ़लाइन",
			cn: "离线",
		},
		sync_DENIED: {
			en: "Denied",
			pt: "Negado",
			es: "Denegado",
			hi: "अस्वीकृत",
			cn: "拒绝",
		},
		sync_ERROR: {
			en: "Error",
			pt: "Erro",
			es: "Error",
			hi: "त्रुटि",
			cn: "错误",
		},
	},
	landing: {
		failed: {
			en: "Login failed, please try again",
			pt: "Login falhou, por favor tente novamente",
			es: "Inicio de sesión fallido, por favor intente de nuevo",
			hi: "लॉगिन विफल, कृपया पुनः प्रयास करें",
			cn: "登录失败，请重试",
		},
		welcome: {
			en: "Please check your email.",
			pt: "Por favor, verifique seu e-mail.",
			es: "Por favor, revise su correo electrónico.",
			hi: "कृपया अपना ईमेल जांचें।",
			cn: "请检查您的电子邮件。",
		},
		title: {
			en: "Introducing Moneeey",
			pt: "Apresentando Moneeey",
			es: "Presentando Moneeey",
			hi: "मनी की शुरुआत",
			cn: "介绍Moneeey",
		},
		messages: {
			en: [
				"Budget with ease using Moneeey's intuitive interface",
				"Achieve financial independence and live life to the fullest",
				"Take ownership of your sensitive information",
				"Built with privacy and security in mind",
				"Enjoy end-to-end encryption for maximum data protection",
				"Seamlessly import and export your financial data",
			],
			pt: [
				"Orçamento com facilidade usando a interface intuitiva do Moneeey",
				"Alcance a independência financeira e viva a vida ao máximo",
				"Assuma o controle de suas informações sensíveis",
				"Construído com privacidade e segurança em mente",
				"Aproveite a criptografia de ponta a ponta para máxima proteção de dados",
				"Importe e exporte seus dados financeiros sem problemas",
			],
			es: [
				"Presupueste con facilidad utilizando la interfaz intuitiva de Moneeey",
				"Logre la independencia financiera y viva la vida al máximo",
				"Tome posesión de su información sensible",
				"Construido con la privacidad y seguridad en mente",
				"Disfrute de la encriptación de extremo a extremo para la máxima protección de datos",
				"Importe y exporte sus datos financieros sin problemas",
			],
			hi: [
				"मनी की सहज इंटरफ़ेस के साथ आसानी से बजट बनाएं",
				"वित्तीय स्वतंत्रता प्राप्त करें और जीवन का पूरा आनंद लें",
				"अपनी संवेदनशील जानकारी पर स्वामित्व प्राप्त करें",
				"गोपनीयता और सुरक्षा को ध्यान में रखकर बनाया गया",
				"अधिकतम डेटा सुरक्षा के लिए एंड-टू-एंड एन्क्रिप्शन का आनंद लें",
				"अपने वित्तीय डेटा को सहजता से आयात और निर्यात करें",
			],
			cn: [
				"使用 Moneeey 的直观界面轻松管理预算",
				"实现财务独立，尽情享受生活",
				"掌控您的敏感信息",
				"专为隐私和安全打造",
				"享受端到端加密，确保最大程度的数据保护",
				"无缝导入和导出您的财务数据",
			],
		},
	},
	login: {
		completed: {
			en: "Welcome, please wait...",
			pt: "Bem-vindo, por favor aguarde...",
			es: "Bienvenido, por favor espere...",
			hi: "स्वागत है, कृपया प्रतीक्षा करें...",
			cn: "欢迎，请稍候...",
		},
		auth_code: {
			en: "Bad authentication code, please try again",
			pt: "Código de autenticação incorreto, por favor tente novamente",
			es: "Código de autenticación incorrecto, por favor intente de nuevo",
			hi: "गलत प्रमाणीकरण कोड, कृपया पुनः प्रयास करें",
			cn: "错误的认证代码，请重试",
		},
		confirm_code: {
			en: "Bad confirm code, please try again",
			pt: "Código de confirmação incorreto, por favor tente novamente",
			es: "Código de confirmación incorrecto, por favor intente de nuevo",
			hi: "गलत पुष्टि कोड, कृपया पुनः प्रयास करें",
			cn: "错误的确认代码，请重试",
		},
		code_expired: {
			en: "Confirm code expired, please try again",
			pt: "Código de confirmação expirado, por favor tente novamente",
			es: "Código de confirmación caducado, por favor intente de nuevo",
			hi: "पुष्टि कोड समाप्त हो गया, कृपया पुनः प्रयास करें",
			cn: "确认代码已过期，请重试",
		},
		login_or_signup: {
			en: "Login or Sign up",
			pt: "Entrar ou Inscrever-se",
			es: "Iniciar sesión o Registrarse",
			hi: "लॉगिन करें या साइन अप करें",
			cn: "登录或注册",
		},
		email: {
			en: "Email",
			pt: "E-mail",
			es: "Correo electrónico",
			hi: "ईमेल",
			cn: "电子邮件",
		},
		logout: {
			en: "Logout",
			pt: "Sair",
			es: "Cerrar sesión",
			hi: "लॉगआउट",
			cn: "登出",
		},
	},
	import: {
		start: {
			en: "New import",
			pt: "Nova importação",
			es: "Nueva importación",
			hi: "नया आयात",
			cn: "新导入",
		},
		processing: {
			en: "Importing...",
			pt: "Importando...",
			es: "Importando...",
			hi: "आयात किया जा रहा है...",
			cn: "正在导入...",
		},
		success: {
			en: (fileName: string) =>
				`We found these transactions in "${fileName}". Please confirm the transaction from/to accounts, updating errors, so Moneeey will learn and improve future imports.`,
			pt: (fileName: string) =>
				`Encontramos essas transações em "${fileName}". Por favor, confirme as contas de transação de origem/destino, atualizando erros, assim o Moneeey aprenderá e melhorará futuras importações.`,
			es: (fileName: string) =>
				`Encontramos estas transacciones en "${fileName}". Por favor, confirme las cuentas de origen/destino de la transacción, actualizando errores, para que Moneeey aprenda y mejore futuras importaciones.`,
			hi: (fileName: string) =>
				`हमें "${fileName}" में ये लेन-देन मिले। कृपया खातों से/तक लेन-देन की पुष्टि करें, त्रुटियों को अपडेट करें ताकि मनी सीख सके और भविष्य के आयात में सुधार कर सके।`,
			cn: (fileName: string) =>
				`我们在 "${fileName}" 中找到了这些交易。请确认从/到账户的交易，更新错误，以便 Moneeey 学习并改进未来的导入。`,
		},
		drop_here: {
			en: "Drop the files here ...",
			pt: "Solte os arquivos aqui ...",
			es: "Suelte los archivos aquí ...",
			hi: "फाइलों को यहाँ छोड़ें ...",
			cn: "拖放文件到这里...",
		},
		click_or_drop_here: {
			en: "Drag and drop files here, or click to select files",
			pt: "Arraste e solte arquivos aqui, ou clique para selecionar arquivos",
			es: "Arrastre y suelte archivos aquí, o haga clic para seleccionar archivos",
			hi: "यहाँ फाइलों को खींचें और छोड़ें, या फाइलें चुनने के लिए क्लिक करें",
			cn: "拖放文件到这里，或点击选择文件",
		},
		supported_formats: {
			en: "Supported formats: TXT, CSV, OFX, PDF",
			pt: "Formatos suportados: TXT, CSV, OFX, PDF",
			es: "Formatos compatibles: TXT, CSV, OFX, PDF",
			hi: "समर्थित प्रारूप: TXT, CSV, OFX, PDF",
			cn: "支持的格式：TXT、CSV、OFX、PDF",
		},
		unknown_mode: {
			en: (mode: string) => `Unknown mode ${mode}`,
			pt: (mode: string) => `Modo desconhecido ${mode}`,
			es: (mode: string) => `Modo desconocido ${mode}`,
			hi: (mode: string) => `अज्ञात मोड ${mode}`,
			cn: (mode: string) => `未知模式 ${mode}`,
		},
		new_import: {
			en: "New import",
			pt: "Nova importação",
			es: "Nueva importación",
			hi: "नया आयात",
			cn: "新导入",
		},
		configuration: {
			en: "Configuration",
			pt: "Configuração",
			es: "Configuración",
			hi: "कॉन्फ़िगरेशन",
			cn: "配置",
		},
		select_reference_account: {
			en: "Please select reference account",
			pt: "Por favor, selecione a conta de referência",
			es: "Por favor seleccione la cuenta de referencia",
			hi: "कृपया संदर्भ खाता चुनें",
			cn: "请选择参考账户",
		},
		updated: {
			en: "Updated",
			pt: "Atualizado",
			es: "Actualizado",
			hi: "अद्यतन किया गया",
			cn: "已更新",
		},
		existing: {
			en: "Existing",
			pt: "Existente",
			es: "Existente",
			hi: "मौजूदा",
			cn: "现有",
		},
		new: {
			en: "New",
			pt: "Novo",
			es: "Nuevo",
			hi: "नया",
			cn: "新的",
		},
		unchanged: {
			en: "Unchanged",
			pt: "Inalterado",
			es: "Sin cambios",
			hi: "बिना बदले",
			cn: "未更改",
		},
		import_transactions: {
			en: "Import transactions",
			pt: "Importar transações",
			es: "Importar transacciones",
			hi: "लेन-देन आयात करें",
			cn: "导入交易",
		},
		invert_from_to_accounts: {
			en: "Invert from and to accounts",
			pt: "Inverter contas de origem e destino",
			es: "Invertir cuentas de origen y destino",
			hi: "खाते से और खाते में उलटें",
			cn: "反转来源和目标账户",
		},
		changed_description: {
			en: (from_value: string, to_value: string) =>
				`Changed from\n${from_value}\nto\n${to_value}`,
			pt: (from_value: string, to_value: string) =>
				`Alterado de\n${from_value}\npara\n${to_value}`,
			es: (from_value: string, to_value: string) =>
				`Cambiado de\n${from_value}\na\n${to_value}`,
			hi: (from_value: string, to_value: string) =>
				`${from_value}\nसे बदलकर\n${to_value}\nकिया गया`,
			cn: (from_value: string, to_value: string) =>
				`从\n${from_value}\n更改为\n${to_value}`,
		},
	},
	util: {
		name: {
			en: "Name",
			pt: "Nome",
			es: "Nombre",
			hi: "नाम",
			cn: "名称",
		},
		tags: {
			en: "Tags",
			pt: "Tags",
			es: "Etiquetas",
			hi: "टैग्स",
			cn: "标签",
		},
		archived: {
			en: "Archived",
			pt: "Arquivado",
			es: "Archivado",
			hi: "संग्रहीत",
			cn: "已归档",
		},
		close: {
			en: "Close",
			pt: "Fechar",
			es: "Cerrar",
			hi: "बंद करें",
			cn: "关闭",
		},
		created: {
			en: "Created",
			pt: "Criado",
			es: "Creado",
			hi: "बनाया गया",
			cn: "已创建",
		},
		delete: {
			en: "Delete",
			pt: "Excluir",
			es: "Eliminar",
			hi: "हटाएं",
			cn: "删除",
		},
		currency: {
			en: "Currency",
			pt: "Moeda",
			es: "Moneda",
			hi: "मुद्रा",
			cn: "货币",
		},
		date: {
			en: "Date",
			pt: "Data",
			es: "Fecha",
			hi: "तारीख",
			cn: "日期",
		},
		date_format: {
			en: "Date format",
			pt: "Formato da data",
			es: "Formato de fecha",
			hi: "तारीख प्रारूप",
			cn: "日期格式",
		},
		loading: {
			en: "Loading...",
			pt: "Carregando...",
			es: "Cargando...",
			hi: "लोड हो रहा है...",
			cn: "加载中...",
		},
		day: {
			en: "Day",
			pt: "Dia",
			es: "Día",
			hi: "दिन",
			cn: "天",
		},
		week: {
			en: "Week",
			pt: "Semana",
			es: "Semana",
			hi: "सप्ताह",
			cn: "周",
		},
		month: {
			en: "Month",
			pt: "Mês",
			es: "Mes",
			hi: "महीना",
			cn: "月",
		},
		quarter: {
			en: "Quarter",
			pt: "Trimestre",
			es: "Trimestre",
			hi: "तिमाही",
			cn: "季度",
		},
		year: {
			en: "Year",
			pt: "Ano",
			es: "Año",
			hi: "वर्ष",
			cn: "年",
		},
		ok: {
			en: "Ok",
			pt: "Ok",
			es: "Aceptar",
			hi: "ठीक है",
			cn: "确定",
		},
		cancel: {
			en: "Cancel",
			pt: "Cancelar",
			es: "Cancelar",
			hi: "रद्द करें",
			cn: "取消",
		},
		clear: {
			en: "Clear",
			pt: "Limpar",
			es: "Limpiar",
			hi: "साफ करें",
			cn: "清除",
		},
		required: {
			en: "Required",
			pt: "Requerido",
			es: "Requerido",
			hi: "आवश्यक",
			cn: "必填",
		},
		empty: {
			en: "Empty",
			pt: "Vazio",
			es: "Vacío",
			hi: "खाली",
			cn: "空的",
		},
	},
	settings: {
		locale: {
			en: "Locale",
			pt: "Localização",
			es: "Localización",
			hi: "स्थान",
			cn: "区域设置",
		},
		reload_page: {
			en: "Reload your page",
			pt: "Recarregue sua página",
			es: "Recargue su página",
			hi: "अपने पृष्ठ को पुनः लोड करें",
			cn: "重新加载页面",
		},
		export_data: {
			en: "Export data",
			pt: "Exportar dados",
			es: "Exportar datos",
			hi: "डेटा निर्यात करें",
			cn: "导出数据",
		},
		import_data: {
			en: "Import data",
			pt: "Importar dados",
			es: "Importar datos",
			hi: "डेटा आयात करें",
			cn: "导入数据",
		},
		clear_all: {
			en: "Clear all data",
			pt: "Limpar todos os dados",
			es: "Borrar todos los datos",
			hi: "सभी डेटा साफ़ करें",
			cn: "清除所有数据",
		},
		default_currency: {
			en: "Default currency",
			pt: "Moeda padrão",
			es: "Moneda predeterminada",
			hi: "डिफ़ॉल्ट मुद्रा",
			cn: "默认货币",
		},
		reference_account: {
			en: "Reference account",
			pt: "Conta de referência",
			es: "Cuenta de referencia",
			hi: "संदर्भ खाता",
			cn: "参考账户",
		},
		decimal_separator: {
			en: "Decimal separator",
			pt: "Separador decimal",
			es: "Separador decimal",
			hi: "दशमलव विभाजक",
			cn: "小数分隔符",
		},
		thousand_separator: {
			en: "Thousand separator",
			pt: "Separador de milhar",
			es: "Separador de miles",
			hi: "हजार विभाजक",
			cn: "千位分隔符",
		},
		backup_loading: {
			en: (percentage: number) =>
				`Loading your backup data, please wait... ${percentage}%`,
			pt: (percentage: number) =>
				`Carregando seus dados de backup, por favor aguarde... ${percentage}%`,
			es: (percentage: number) =>
				`Cargando sus datos de respaldo, por favor espere... ${percentage}%`,
			hi: (percentage: number) =>
				`आपका बैकअप डेटा लोड हो रहा है, कृपया प्रतीक्षा करें... ${percentage}%`,
			cn: (percentage: number) =>
				`正在加载您的备份数据，请稍候... ${percentage}%`,
		},
		restore_loading: {
			en: (percentage: number) =>
				`Restoring your backup data, please wait... ${percentage}%`,
			pt: (percentage: number) =>
				`Restaurando seus dados de backup, por favor aguarde... ${percentage}%`,
			es: (percentage: number) =>
				`Restaurando sus datos de respaldo, por favor espere... ${percentage}%`,
			hi: (percentage: number) =>
				`आपका बैकअप डेटा पुनर्स्थापित हो रहा है, कृपया प्रतीक्षा करें... ${percentage}%`,
			cn: (percentage: number) =>
				`正在恢复您的备份数据，请稍候... ${percentage}%`,
		},
		restore_data_placeholder: {
			en: "Paste your restore data here and click 'Restore data' again",
			pt: "Cole seus dados de restauração aqui e clique em 'Restaurar dados' novamente",
			es: "Pegue sus datos de restauración aquí y haga clic en 'Restaurar datos' nuevamente",
			hi: "यहाँ अपने पुनर्स्थापना डेटा को पेस्ट करें और 'डेटा पुनर्स्थापित करें' पर फिर से क्लिक करें",
			cn: "在此粘贴您的恢复数据，然后再次点击‘恢复数据’",
		},
		clear_data_token: {
			en: "DELETE EVERYTHING",
			pt: "EXCLUIR TUDO",
			es: "ELIMINAR TODO",
			hi: "सब कुछ हटा दें",
			cn: "删除所有内容",
		},
		clear_data_placeholder: {
			en: "Type 'DELETE EVERYTHING' in this text area and hit 'Clear data' again to delete everything and start from zero.",
			pt: "Digite 'EXCLUIR TUDO' nesta área de texto e pressione 'Limpar dados' novamente para excluir tudo e começar do zero.",
			es: "Escriba 'ELIMINAR TODO' en esta área de texto y presione 'Borrar datos' nuevamente para eliminar todo y comenzar desde cero.",
			hi: "इस टेक्स्ट क्षेत्र में 'सब कुछ हटा दें' टाइप करें और फिर 'डेटा साफ़ करें' दबाएँ ताकि सब कुछ हट जाए और शुरुआत से शुरू किया जा सके।",
			cn: "在此文本框中输入‘删除所有内容’，然后再次点击‘清除数据’以删除所有数据并从零开始。",
		},
		create_entity: {
			en: (entity: string) => `Create ${entity}`,
			pt: (entity: string) => `Criar ${entity}`,
			es: (entity: string) => `Crear ${entity}`,
			hi: (entity: string) => `${entity} बनाएं`,
			cn: (entity: string) => `创建 ${entity}`,
		},
		select_default_currency: {
			en: "Select default currency",
			pt: "Selecionar moeda padrão",
			es: "Seleccionar moneda predeterminada",
			hi: "डिफ़ॉल्ट मुद्रा चुनें",
			cn: "选择默认货币",
		},
		select_language: {
			en: "Select language",
			pt: "Selecionar linguagem",
			es: "Seleccionar idioma",
			hi: "भाषा चुनें",
			cn: "选择语言",
		},
	},
	budget: {
		budget: {
			en: "Budget",
			pt: "Orçamento",
			es: "Presupuesto",
			hi: "बजट",
			cn: "预算",
		},
		new: {
			en: "New budget",
			pt: "Novo orçamento",
			es: "Nuevo presupuesto",
			hi: "नया बजट",
			cn: "新预算",
		},
		next: {
			en: "Next",
			pt: "Próximo",
			es: "Siguiente",
			hi: "अगला",
			cn: "下一步",
		},
		prev: {
			en: "Prev",
			pt: "Anterior",
			es: "Anterior",
			hi: "पिछला",
			cn: "上一步",
		},
		save: {
			en: "Save",
			pt: "Salvar",
			es: "Guardar",
			hi: "सहेजें",
			cn: "保存",
		},
		show_months: {
			en: "Visible months",
			pt: "Meses visíveis",
			es: "Meses visibles",
			hi: "दिखने वाले महीने",
			cn: "可见月份",
		},
		show_archived: {
			en: "Show archived budgets",
			pt: "Mostrar orçamentos arquivados",
			es: "Mostrar presupuestos archivados",
			hi: "संग्रहीत बजट दिखाएं",
			cn: "显示已归档预算",
		},
		allocated: {
			en: "Allocated",
			pt: "Alocado",
			es: "Asignado",
			hi: "आवंटित",
			cn: "已分配",
		},
		used: {
			en: "Used",
			pt: "Usado",
			es: "Usado",
			hi: "उपयोग किया गया",
			cn: "已使用",
		},
		remaining: {
			en: "Remaining",
			pt: "Restante",
			es: "Restante",
			hi: "शेष",
			cn: "剩余",
		},
		format_example: {
			en: (fromAccount: string, toAccount: string, amount: string) =>
				`${fromAccount} -> ${toAccount}: ${amount}`,
			pt: (fromAccount: string, toAccount: string, amount: string) =>
				`${fromAccount} -> ${toAccount}: ${amount}`,
			es: (fromAccount: string, toAccount: string, amount: string) =>
				`${fromAccount} -> ${toAccount}: ${amount}`,
			hi: (fromAccount: string, toAccount: string, amount: string) =>
				`${fromAccount} -> ${toAccount}: ${amount}`,
			cn: (fromAccount: string, toAccount: string, amount: string) =>
				`${fromAccount} -> ${toAccount}: ${amount}`,
		},
	},
	account: {
		add_account: {
			en: "Create account",
			pt: "Adicionar conta",
			es: "Nueva cuenta",
			hi: "खाता बनाएँ",
			cn: "创建账户",
		},
		offbudget: {
			en: "Off-Budget",
			pt: "Fora do orçamento",
			es: "Fuera del presupuesto",
			hi: "बजट से बाहर",
			cn: "非预算",
		},
		account_kind: {
			en: "Type",
			pt: "Tipo",
			es: "Tipo",
			hi: "प्रकार",
			cn: "类型",
		},
		kind_CHECKING: {
			en: "Checking Account",
			pt: "Conta Corrente",
			es: "Cuenta corriente",
			hi: "चेकिंग खाता",
			cn: "支票账户",
		},
		kind_CREDIT_CARD: {
			en: "Credit Card",
			pt: "Cartão de Crédito",
			es: "Tarjeta de crédito",
			hi: "क्रेडिट कार्ड",
			cn: "信用卡",
		},
		kind_INVESTMENT: {
			en: "Investment Account",
			pt: "Conta de Investimento",
			es: "Cuenta de inversión",
			hi: "निवेश खाता",
			cn: "投资账户",
		},
		kind_PAYEE: {
			en: "Payee",
			pt: "Beneficiário",
			es: "Beneficiario",
			hi: "प्राप्तकर्ता",
			cn: "收款人",
		},
		kind_SAVINGS: {
			en: "Savings Account",
			pt: "Conta Poupança",
			es: "Cuenta de ahorros",
			hi: "बचत खाता",
			cn: "储蓄账户",
		},
	},
	new_account: {
		name: {
			en: "New account name",
			pt: "Novo nome da conta",
			es: "Nuevo nombre de cuenta",
			hi: "नए खाते का नाम",
			cn: "新账户名称",
		},
		type: {
			en: "Kind",
			pt: "Tipo",
			es: "Tipo",
			hi: "प्रकार",
			cn: "类型",
		},
		currency: {
			en: "Currency",
			pt: "Moeda",
			es: "Moneda",
			hi: "मुद्रा",
			cn: "货币",
		},
		initial_balance: {
			en: "Initial balance",
			pt: "Saldo inicial",
			es: "Saldo inicial",
			hi: "प्रारंभिक शेष राशि",
			cn: "初始余额",
		},
		submit_close: {
			en: "Save and close",
			pt: "Salvar e fechar",
			es: "Guardar y cerrar",
			hi: "सहेजें और बंद करें",
			cn: "保存并关闭",
		},
		submit_another: {
			en: "Save and add another",
			pt: "Salvar e adicionar outro",
			es: "Guardar y añadir otro",
			hi: "सहेजें और एक और जोड़ें",
			cn: "保存并添加另一个",
		},
	},
	currencies: {
		short: {
			en: "Short",
			pt: "Nome",
			es: "Nombre",
			hi: "संक्षिप्त नाम",
			cn: "简称",
		},
		prefix: {
			en: "Prefix",
			pt: "Prefixo",
			es: "Prefijo",
			hi: "उपसर्ग",
			cn: "前缀",
		},
		suffix: {
			en: "Suffix",
			pt: "Sufixo",
			es: "Sufijo",
			hi: "प्रत्यय",
			cn: "后缀",
		},
		decimals: {
			en: "Decimals",
			pt: "Decimais",
			es: "Decimales",
			hi: "दशमलव",
			cn: "小数位",
		},
	},
	transactions: {
		amount: {
			en: "Amount",
			pt: "Valor",
			es: "Monto",
			hi: "राशि",
			cn: "金额",
		},
		memo: {
			en: "Memo",
			pt: "Memo",
			es: "Memo",
			hi: "मेमो",
			cn: "备忘录",
		},
		from_account: {
			en: "From",
			pt: "De",
			es: "Desde",
			hi: "से",
			cn: "从",
		},
		to_account: {
			en: "To",
			pt: "Para",
			es: "Hacia",
			hi: "को",
			cn: "到",
		},
		running_balance: {
			en: "Running",
			pt: "Saldo em execução",
			es: "Saldo actual",
			hi: "चल रही शेष राशि",
			cn: "运行余额",
		},
	},
	dashboard: {
		recent_transactions: {
			en: "Recent transactions",
			pt: "Transações recentes",
			es: "Transacciones recientes",
			hi: "हाल की लेन-देन",
			cn: "最近交易",
		},
	},

	reports: {
		account_balance: {
			en: "Account balance",
			pt: "Saldo da conta",
			es: "Saldo de la cuenta",
			hi: "खाते की शेष राशि",
			cn: "账户余额",
		},
		payee_balance: {
			en: "Payee balance",
			pt: "Saldo do beneficiário",
			es: "Saldo del beneficiario",
			hi: "प्राप्तकर्ता की शेष राशि",
			cn: "收款人余额",
		},
		tag_expenses: {
			en: "Tag expenses",
			pt: "Despesas de tag",
			es: "Gastos de etiqueta",
			hi: "टैग खर्च",
			cn: "标签支出",
		},
		wealth_growth: {
			en: "Wealth growth",
			pt: "Crescimento da riqueza",
			es: "Crecimiento de la riqueza",
			hi: "सम्पत्ति वृद्धि",
			cn: "财富增长",
		},
		income_vs_expenses: {
			en: "Income vs Expenses",
			pt: "Renda vs Despesas",
			es: "Ingresos vs Gastos",
			hi: "आय बनाम खर्च",
			cn: "收入与支出",
		},
		wealth: {
			en: "Wealth",
			pt: "Riqueza",
			es: "Riqueza",
			hi: "सम्पत्ति",
			cn: "财富",
		},
		income: {
			en: "Income",
			pt: "Renda",
			es: "Ingresos",
			hi: "आय",
			cn: "收入",
		},
		expense: {
			en: "Expense",
			pt: "Despesa",
			es: "Gastos",
			hi: "खर्च",
			cn: "支出",
		},
		include_accounts: {
			en: "Include accounts:",
			pt: "Incluir contas:",
			es: "Incluir cuentas:",
			hi: "खाते शामिल करें:",
			cn: "包括账户：",
		},
	},

	modal: {
		landing: {
			en: "Welcome to Moneeey",
			pt: "Bem-vindo ao Moneeey",
			es: "Bienvenido a Moneeey",
			hi: "मनी में आपका स्वागत है",
			cn: "欢迎来到 Moneeey",
		},
		start_tour: {
			en: "Start Tour",
			pt: "Iniciar Tour",
			es: "Comenzar Tour",
			hi: "यात्रा शुरू करें",
			cn: "开始游览",
		},
		sync: {
			en: "Sync",
			pt: "Sincronizar",
			es: "Sincronizar",
			hi: "सिंक करें",
			cn: "同步",
		},
		merge_accounts: {
			en: "Merge accounts",
			pt: "Mesclar contas",
			es: "Fusionar cuentas",
			hi: "खाते मर्ज करें",
			cn: "合并账户",
		},
	},

	merge_accounts: {
		submit: {
			en: "Merge accounts",
			pt: "Mesclar contas",
			es: "Fusionar cuentas",
			hi: "खाते मर्ज करें",
			cn: "合并账户",
		},
		description: {
			en: "Merge two accounts into a single one, moving all transactions from the source account to the target account.",
			pt: "Mesclar duas contas em uma única, movendo todas as transações da conta de origem para a conta de destino.",
			es: "Fusionar dos cuentas en una sola, moviendo todas las transacciones de la cuenta de origen a la cuenta de destino.",
			hi: "दो खातों को एक में मर्ज करें, स्रोत खाते से सभी लेन-देन को लक्ष्य खाते में स्थानांतरित करें।",
			cn: "将两个账户合并为一个，将所有交易从源账户移动到目标账户。",
		},
		source: {
			en: "Source account (deleted)",
			pt: "Conta de origem (excluída)",
			es: "Cuenta de origen (eliminada)",
			hi: "स्रोत खाता (हटा दिया गया)",
			cn: "源账户（已删除）",
		},
		target: {
			en: "Target account (merged into)",
			pt: "Conta de destino (mesclada)",
			es: "Cuenta de destino (fusionada)",
			hi: "लक्ष्य खाता (जिसमें मर्ज किया गया)",
			cn: "目标账户（已合并）",
		},
		success: {
			en: "Accounts merged successfully",
			pt: "Contas mescladas com sucesso",
			es: "Cuentas fusionadas con éxito",
			hi: "खाते सफलतापूर्वक मर्ज किए गए",
			cn: "账户合并成功",
		},
	},

	sync: {
		intro: {
			en: "Synchronizing your data allows real-time multi-device use of Moneeey, even supporting collaboration.",
			pt: "Sincronizar seus dados permite o uso do Moneeey em vários dispositivos em tempo real, até mesmo para colaboração.",
			es: "Sincronizar sus datos permite el uso de Moneeey en múltiples dispositivos en tiempo real, incluso para colaboración.",
			hi: "अपने डेटा को सिंक्रनाइज़ करने से आप कई उपकरणों पर रियल-टाइम में मनी का उपयोग कर सकते हैं, यहां तक कि सहयोग का समर्थन भी कर सकते हैं।",
			cn: "同步您的数据可实现 Moneeey 在多个设备上的实时使用，甚至支持协作。",
		},
		login_success: {
			en: "Successful login!",
			pt: "Login bem-sucedido!",
			es: "¡Inicio de sesión exitoso!",
			hi: "सफल लॉगिन!",
			cn: "登录成功！",
		},
		login_started: {
			en: "A confirmation email has been sent. Please confirm by clicking the link.",
			pt: "Um e-mail de confirmação foi enviado. Por favor, confirme clicando no link.",
			es: "Se ha enviado un correo de confirmación. Por favor, confirme haciendo clic en el enlace.",
			hi: "एक पुष्टि ईमेल भेजी गई है। कृपया लिंक पर क्लिक करके पुष्टि करें।",
			cn: "确认邮件已发送。请点击链接确认。",
		},
		login_error: {
			en: "Unable to send login confirmation email.",
			pt: "Não foi possível enviar o e-mail de confirmação de login.",
			es: "No se pudo enviar el correo de confirmación de inicio de sesión.",
			hi: "लॉगिन पुष्टि ईमेल भेजने में असमर्थ।",
			cn: "无法发送登录确认邮件。",
		},
		couchdb_url: {
			en: "CouchDB URL",
			pt: "URL do CouchDB",
			es: "URL de CouchDB",
			hi: "CouchDB URL",
			cn: "CouchDB 地址",
		},
		couchdb_username: {
			en: "CouchDB Username",
			pt: "Nome de usuário do CouchDB",
			es: "Nombre de usuario de CouchDB",
			hi: "CouchDB उपयोगकर्ता नाम",
			cn: "CouchDB 用户名",
		},
		couchdb_password: {
			en: "CouchDB Password",
			pt: "Senha do CouchDB",
			es: "Contraseña de CouchDB",
			hi: "CouchDB पासवर्ड",
			cn: "CouchDB 密码",
		},
		start: {
			en: "Start synchronization",
			pt: "Iniciar sincronização",
			es: "Iniciar sincronización",
			hi: "सिंक शुरू करें",
			cn: "开始同步",
		},
		stop: {
			en: "Stop synchronization",
			pt: "Parar sincronização",
			es: "Detener sincronización",
			hi: "सिंक रोकें",
			cn: "停止同步",
		},
		moneeey_sync: {
			en: "Moneeey Sync",
			pt: "Moneeey Sync",
			es: "Moneeey Sync",
			hi: "मनी सिंक",
			cn: "Moneeey 同步",
		},
		database_sync: {
			en: "Custom",
			pt: "Custom",
			es: "Custom",
			hi: "कस्टम",
			cn: "自定义",
		},
	},

	tour: {
		welcome: {
			en: "Welcome to Moneeey",
			pt: "Bem-vindo ao Moneeey",
			es: "Bienvenido a Moneeey",
			hi: "मनी में आपका स्वागत है",
			cn: "欢迎来到 Moneeey",
		},
		next: {
			en: "Next",
			pt: "Próximo",
			es: "Siguiente",
			hi: "अगला",
			cn: "下一步",
		},
		prev: {
			en: "Previous",
			pt: "Anterior",
			es: "Anterior",
			hi: "पिछला",
			cn: "上一步",
		},
		continue_language: {
			en: "Continue to default currency selection",
			pt: "Continuar para seleção de moeda padrão",
			es: "Continuar a la selección de moneda predeterminada",
			hi: "डिफ़ॉल्ट मुद्रा चयन पर जारी रखें",
			cn: "继续选择默认货币",
		},
		continue_currency: {
			en: "Continue to Moneeey",
			pt: "Continuar para Moneeey",
			es: "Continuar a Moneeey",
			hi: "मनी पर जारी रखें",
			cn: "继续使用 Moneeey",
		},
		import: {
			en: "You can import transactions from common banking formats.",
			pt: "Você pode importar transações de formatos bancários comuns.",
			es: "Puede importar transacciones desde formatos bancarios comunes.",
			hi: "आप सामान्य बैंकिंग प्रारूपों से लेन-देन आयात कर सकते हैं।",
			cn: "您可以从常见的银行格式导入交易。",
		},
		currencies: {
			en: "Moneeey is multi-currency! We have added the 50 most used currencies in the world. Feel free to add or customize as you like!",
			pt: "O Moneeey é multimoeda! Adicionamos as 50 moedas mais usadas no mundo. Sinta-se à vontade para adicionar ou personalizar como quiser!",
			es: "¡Moneeey es multimoneda! Hemos añadido las 50 monedas más utilizadas en el mundo. ¡Siéntase libre de agregar o personalizar como desee!",
			hi: "मनी बहु-मुद्रा समर्थित है! हमने दुनिया की 50 सबसे अधिक उपयोग की जाने वाली मुद्राएँ जोड़ी हैं। आप उन्हें अपनी आवश्यकताओं के अनुसार जोड़ या अनुकूलित कर सकते हैं!",
			cn: "Moneeey 支持多种货币！我们已添加全球 50 种最常用的货币。请随意添加或自定义！",
		},
		accounts: {
			en: "Manage your accounts in this section. You can add new accounts, change currencies, and archive accounts.",
			pt: "Gerencie suas contas nesta seção. Você pode adicionar novas contas, alterar moedas e arquivar contas.",
			es: "Administre sus cuentas en esta sección. Puede agregar nuevas cuentas, cambiar monedas y archivar cuentas.",
			hi: "इस अनुभाग में अपने खातों का प्रबंधन करें। आप नए खाते जोड़ सकते हैं, मुद्राएँ बदल सकते हैं और खातों को संग्रहीत कर सकते हैं।",
			cn: "在此部分管理您的账户。您可以添加新账户、更改货币和归档账户。",
		},
		transactions: {
			en: "Moneeey generates reports and insights based on your transactions. Add new payees easily by typing a name and selecting 'Create'.",
			pt: "O Moneeey gera relatórios e insights com base nas suas transações. Adicione novos beneficiários facilmente digitando um nome e selecionando 'Criar'.",
			es: "Moneeey genera informes y análisis basados en sus transacciones. Agregue nuevos beneficiarios fácilmente escribiendo un nombre y seleccionando 'Crear'.",
			hi: "मनी आपके लेन-देन के आधार पर रिपोर्ट और अंतर्दृष्टि उत्पन्न करता है। नाम टाइप करके और 'बनाएँ' चुनकर आसानी से नए प्राप्तकर्ता जोड़ें।",
			cn: "Moneeey 根据您的交易生成报告和见解。输入名称并选择‘创建’即可轻松添加新的收款人。",
		},
		budgets: {
			en: "Time to budget your Moneeey! Allocate parts of your income to budgets and track your financial goals.",
			pt: "Hora de orçar seu Moneeey! Aloque partes de sua renda em orçamentos e acompanhe suas metas financeiras.",
			es: "¡Es hora de presupuestar su Moneeey! Asigne partes de sus ingresos a presupuestos y siga sus objetivos financieros.",
			hi: "अब अपने मनी का बजट बनाएं! अपनी आय के हिस्सों को बजट में आवंटित करें और अपने वित्तीय लक्ष्यों को ट्रैक करें।",
			cn: "是时候为您的 Moneeey 设定预算了！将您的收入分配到预算中，并跟踪您的财务目标。",
		},
		your_turn: {
			en: "Now it's your turn! Start adding transactions to get real insights.",
			pt: "Agora é a sua vez! Comece a adicionar transações para obter insights reais.",
			es: "¡Ahora es tu turno! Comience a agregar transacciones para obtener información real.",
			hi: "अब आपकी बारी है! वास्तविक अंतर्दृष्टि प्राप्त करने के लिए लेन-देन जोड़ना शुरू करें।",
			cn: "现在轮到您了！开始添加交易，以获取真实的见解。",
		},
		please_create_budget: {
			en: "Before continuing, click 'New Budget' and create a budget.",
			pt: "Antes de continuar, clique em 'Novo Orçamento' e crie um orçamento.",
			es: "Antes de continuar, haga clic en 'Nuevo Presupuesto' y cree un presupuesto.",
			hi: "जारी रखने से पहले, 'नया बजट' पर क्लिक करें और एक बजट बनाएं।",
			cn: "在继续之前，请点击‘新预算’并创建预算。",
		},
		please_create_account: {
			en: "Before continuing, create an account by entering details below.",
			pt: "Antes de continuar, crie uma conta inserindo os detalhes abaixo.",
			es: "Antes de continuar, cree una cuenta ingresando los detalles a continuación.",
			hi: "जारी रखने से पहले, नीचे विवरण दर्ज करके एक खाता बनाएँ।",
			cn: "在继续之前，请输入以下详细信息创建账户。",
		},
	},
} as const;
