name: backend-test
on:
  push:
    paths: [ 'backend' ]
jobs:
  backend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.17'
        cache: 'yarn'
    - run: yarn
    - run: yarn test
