name: CI/CD

on: push

jobs:
  FRONTEND:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "20.11"
          cache: yarn

      - run: yarn install --immutable
        name: Install frontend

      - run: yarn test
        name: Test

      - name: Set up Playwright cache path
        run: echo "PLAYWRIGHT_CACHE=${{ github.workspace }}/playwright-cache" >> $GITHUB_ENV

      - name: Playwright Dependencies cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/playwright-cache
          key: playwright-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Playwright
        uses: addnab/docker-run-action@v3
        with:
          image: mcr.microsoft.com/playwright:v1.36.1-jammy
          options: --rm -v ${{ github.workspace }}:/workspace -v ${{ github.workspace }}/playwright-cache:/root/.cache/ms-playwright
          run: |
            cd /workspace/playwright
            yarn install --immutable
            yarn playwright install --with-deps
            export CI=true
            yarn test --reporter=html,json

      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          working-directory: playwright
          path: |
            playwright-report/
            test-results/videos/
          retention-days: 30

  BACKEND:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.35.3

      - run: deno cache main.ts
        name: Install

      - run: deno test --allow-all
        name: Test

  LINT:
    needs: [FRONTEND]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "20.11"
          cache: yarn

      - run: yarn install --immutable
        name: Install biome

      - run: yarn install --immutable
        name: Install frontend
        working-directory: frontend

      - run: yarn lint
        name: Lint

  PACKAGE:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [FRONTEND, BACKEND]
    strategy:
      matrix:
        service: [backend, frontend]
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}-${{ matrix.service }}
    defaults:
      run:
        working-directory: ${{ matrix.service }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v5

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: docker-${{ runner.os }}-${{ hashFiles('**/Dockerfile.prod', '**/package.json', '**/yarn.lock') }}
          restore-keys: |
            docker-${{ runner.os }}-

      - name: Log into Github Docker registry
        uses: docker/login-action@v5
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile.prod
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
